### ISSUE TITLE
Extend user-defined trailing function capabilities

### ISSUE THREAD

**Issue by L0ric0** [batcholi/XenonCode#3]
Currently a user-defined trailing function must return the same type as the variable it is called on and modifies its value.
This leads to the following pattern when implementing functions working on custom data types:
```
var obj:text = ".start{0}.size{5}.maxSize{100}.array{1,1,1,1,1}

function @Size($buffer : text) : text
    $buffer.return = $buffer.size
    return $buffer

init
    $obj.@Size()
    print($obj.return)
```

Which is hard to read / understand and teaches people new to Programming bad habits. For people already programming it is confusing (Why do I have to modify my object?) and leads to code that is not easy to share (You cant just drop in a replacement for an object / have to figure out how sombody else returns the value you are intrested in, etc.)

When implementing functions like `array.pop` the same problem applies only know you are setting the return value and changing the object itself which makes the code even harder to understand.

Please implement at least user-defined trailing functions that can not modify the object they are called on and can return a different type.

That trailing functions that modify the object and return a different value can not be implemented would be understandable (with all the parameters are copied and no references exist) but still desierable.

**Comment by batcholi** [comment]
Trailing functions are merely syntactic sugar for a less verbose way of doing `$var = @func($var)`
By shortening it with `$var.@func()`
If you don’t intend on modifying/assigning the result of that function back to the object, then don’t use the trailing function idiom.
Simply do`@func($var)`
It’s actually one character less, compared to `$var.@func()` (the dot `.`)
I will close this issue.
